SELECT
    YEAR(o.SALES_DATE) YEAR,
    MONTH(o.SALES_DATE) MONTH,
    COUNT(DISTINCT o.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID)/
    (SELECT count(*)
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    ),1) PUCHASED_RATIO

FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID= o.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR(o.SALES_DATE),MONTH(o.SALES_DATE)
ORDER BY YEAR(o.SALES_DATE),MONTH(o.SALES_DATE);
